### ISSUE TITLE
Class order

### ISSUE THREAD

**Issue by arnaud-lb** [haml/haml-spec#8]
In `HTML-style tag with a CSS class and 'class' as an attribute`, the class declared in attributes is rendered before the class declared as css class:

```
"HTML-style tag with a CSS class and 'class' as an attribute" : {
  "haml" : "%p.class2(class='class1')",
  "html" : "<p class='class1 class2'></p>"
},
```

In `HTML-style tag with a CSS class and 'class' as a variable attribute`, the order is reversed:

```
"HTML-style tag with a CSS class and 'class' as a variable attribute" : {
  "haml" : ".hello(class=var)",
  "html" : "<div class='hello world'></div>",
  "locals" : {
    "var" : "world"
  }
```

Is this expected? Is there a reason for this?

**Comment by dinatih** [comment]
+1

**Comment by hcatlin** [comment]
I would agree that this is unexpected. I would happily accept a test to ensure order based on declaration.

**Comment by hcatlin** [comment]
We have merged in this spec change. Edge Ruby-Haml resolves this.
